apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-antiaffinity3
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: mylabel/database
            operator: In
            values:
            - mysql
        topologyKey: kr
  containers:
  - name: nginx
    image: sjhong1994/chk_pod_info
