apiVersion: v1
kind: Pod
metadata:
  name: nginx-podaffinity-hostname2
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: mylabel/database
            operator: In
            values:
            - mysql
        topologyKey: kubernetes.io/hostname
  containers:
  - name: nginx
    image: sjhong1994/chk_pod_info
