apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
  labels:
    pv: nas
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /n2633384_sjh
    server: 169.254.82.17
